### ISSUE TITLE
Can I get the password of a file already open in my webview?

### ISSUE THREAD

**Issue by cleberrafael** [Nickieros/DecryptXOD-save2PDF#17]
Hello friend, how are you, your tool is excellent, I just have one problem, actually I don't know if it's possible to recover the password xod, it's a book I put on a web server that already preloads using the password, but I lost the pdf with the password would I be able to recover the password of my preloaded xod? maybe in the source code? thanks

**Comment by Nickieros** [comment]
Hi @cleberrafael, I don't know enough about how PDFTron works on the server side and what did you mean by 'book already preloads'. You can search the password in the backend code [e.g. for PHP](https://www.pdftron.com/documentation/php/guides/features/security/decrypt) or in frontend ([usual way](https://www.pdftron.com/documentation/web/guides/features/security/decrypt/) or [Custom Security Handler](https://www.pdftron.com/documentation/web/guides/features/security/pdftron_custom/)). Also, if you can view an encrypted book in PDFTron WebView and the text content inside is not a picture but a real text - then you can inject some JavaScript into FrontEnd to intercept all decrypted parts in WebView and assembly them into a whole file - as it is done in my XOD2XPS tool.

**Comment by cleberrafael** [comment]
Thanks for the quick reply friend, you are amazing I think maybe injecting a javascript would work, would it be possible for you to take a look at the platform? can I pass the data through here or would it have another place? would help me a lot if it did.

I'm not the best at javascript thanks again friend

**Comment by Nickieros** [comment]
leave your contacts here and I will contact you

**Comment by cleberrafael** [comment]
https://t.me/cleberrafael
